#cloud-config
write_files:
  - path: /etc/rancher/rke2/config.yaml
    owner: root:root
    permissions: '0644'
    content: |
      write-kubeconfig-mode: "0644"
      selinux: true
      cni: ${ cni }
      token: ${ random_uuid }
      tls-san:
        %{~ for single_san in san ~}
        - ${ single_san }
        %{~ endfor ~}
      %{~ if taint_servers ~}
      node-taint:
        - "CriticalAddonsOnly=true:NoExecute"
      %{~ endif ~}
      %{~ if length(node_labels) > 0 ~}
      node-label:
      %{~ for label in node_labels ~}
        - "${label}"
      %{~ endfor ~}
      %{~ endif ~}
runcmd:
  - [ sh, -xc, "INSTALL_RKE2_TYPE=server /usr/bin/start_rke2_node.sh" ]
