#cloud-config
write_files:
  - path: /etc/rancher/rke2/config.yaml
    owner: root:root
    permissions: '0644'
    content: |
      selinux: true
      token: ${ random_uuid }
      server: ${ seeder_url }
      %{~ if length(node_labels) > 0 ~}
      node-label:
      %{~ for label in node_labels ~}
        - "${label}"
      %{~ endfor ~}
      %{~ endif ~}
runcmd:
  - [ sh, -xc, "INSTALL_RKE2_TYPE=agent /usr/bin/start_rke2_node.sh" ]
